### PR TITLE
Add back buttons to forms at backend

### PR DESCRIPTION
**Pull request by tanmay3011**

### CODE REVIEW

**Comment by jitendra** [comment]
Please create a helper and use it.

**Comment by tanmay3011** [comment]
@jitendra Helper added! Please review.

**Comment by jitendra** [comment]
:+1: looks good to me but instead of back_to_listing_button, 'back_button' or 'back_to_list_button' sounds more appropriate to me. Please check for its possibility

**Comment by tanmay3011** [comment]
Done!

**Comment by jitendra** [comment]
Great :+1: Please create direct PR

**Pull request closed without merging**
