### PR TITLE
Add shoulda-matcher and shoulda-callback-matcher gems and add write s…

### PR DESCRIPTION
**Pull request by nishant-cyro**
…houlda-matcher configuration in spec_helpers

### CODE REVIEW

**Comment by priyank-gupta** [comment]
@nishant-cyro Add shoulda for sample too.

**Comment by nishant-cyro** [comment]
@priyank-gupta - done!

**Comment by tanmay3011** [comment]
@priyank-gupta @nishant-cyro  Shouldn't we take out Shoulda configuration into a shared path and require it wherever required instead of keeping same code everywhere?

**Comment by priyank-gupta** [comment]
@tanmay3011 Agreed.
@nishant-cyro Lets also make this change.

**Comment by nishant-cyro** [comment]
@priyank-gupta @tanmay3011 - Please let me know if I should add such a file, but I don't want to add a file outside of all gems for a minor spec configuration.

**Comment by nishant-cyro** [comment]
@priyank-gupta @tanmay3011 - done!

**Comment by tanmay3011** [comment]
@nishant-cyro  great! :+1:

**Comment by priyank-gupta** [comment]
:+1: 
Create a direct PR and then close this.

**Comment by nishant-cyro** [comment]
Created a PR, closing this one.

**Pull request closed without merging**
